### ISSUE TITLE
Google Drive Link

### ISSUE THREAD

**Issue by Gagan2002** [EdVince/ClothingTransfer-NCNN#6]
HI,

The Baidu link is not accessible, could you please a google drive link to try your software executable?
thanks in advance

**Comment by EdVince** [comment]
I have check the baiduyun link, it is fine. Are you can not access the baidu?
Because the data is big, but the space of gdrive is always limited.

**Comment by Gagan2002** [comment]
the baiduyin link is blocked in my country. 

can you please upload it to https://wetransfer.com/  my email address is gagan1@gmail.com
also i am giving you my google drive space with writing permissions you cna upload it on below link also
https://drive.google.com/drive/folders/1kH-AII1qsZZGgz8f7b_Y9hsTyPufAWZh?usp=sharing

**Comment by EdVince** [comment]
I have uploaded the models and exe in release, you can download from it.
https://github.com/EdVince/ClothingTransfer-NCNN/releases/tag/storage
